apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications
  labels:
    app: notifications
spec:
  replicas: 4
  selector:
    matchLabels:
      app: notifications
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - name: notifications
          image: saadrehman123/notifications
          envFrom:
            - configMapRef:
                name: notifications-configmap
            - secretRef:
                name: notifications-secret